- app/src/main/java/com/example/breeze0events/OrganizerEventActivity.java
still existing bugs, not fully finished, will finish later
comment everything with bug, will not interfere other parts running
> added new event dialog(not finished)

- app/src/main/java/com/example/breeze0events/AdminEventActivity.java
- app/src/main/java/com/example/breeze0events/AdminOperateActivity.java
- app/src/main/java/com/example/breeze0events/AdminOrganizationProfileActivity.java
- app/src/main/res/layout/admin_main_activity.xml
Update Admin Operate Activity, and create Admin Event Activity for event lists, and create entrant profile and organizer profile for next commits
> AdminOperateActivity update

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/breeze0events/AdminFacilityActivity.java
- app/src/main/java/com/example/breeze0events/AdminLoginActivity.java
- app/src/main/java/com/example/breeze0events/OverallLoginPage.java
- app/src/main/res/layout/admin_facility_page.xml
- app/src/main/res/layout/main_page.xml
Create remove events and facility fragment, and update their UI. Connect overall login page to admin welcome page
> Admin Remove events and facility

- app/src/main/java/com/example/breeze0events/AdminEventDetail.java
- app/src/main/java/com/example/breeze0events/AdminSelectedEvents.java
Issue on event details are not showing correctly info, fix it
> update some event details

- app/src/main/java/com/example/breeze0events/AddFacilityActivity.java
- app/src/main/java/com/example/breeze0events/OrganizerEventActivity.java
- app/src/main/java/com/example/breeze0events/OrganizerMyListActivity.java
- app/src/main/java/com/example/breeze0events/OverallStorageController.java
- app/src/main/res/layout/organizer_event_activity.xml
- app/src/main/res/layout/organizer_main_activity.xml
1. after selected a facility in OrganizerEventActivity, the selected facility will displayed in @+id/selected_facility_text_view properly
2. after clicking "Generate QR Code" button in OrganizerEventActivity, the generated qr code will be displayed in @+id/selected_qr_image_view properly
3. added a "Refresh" button in OrganizerMyListActivity. By clicking it, the content in @+id/organizer_event_list will be refreshed and displayed properly
> Organizer part updates

- app/src/main/java/com/example/breeze0events/AdminEventActivity.java
- app/src/main/java/com/example/breeze0events/AdminEventDetail.java
- app/src/main/java/com/example/breeze0events/AdminQRcode.java
- app/src/main/java/com/example/breeze0events/AdminSelectedEvents.java
- app/src/main/res/layout/qr_code_fragment.xml
> Add QR code and update event

- app/src/main/java/com/example/breeze0events/AdminEventActivity.java
- app/src/main/java/com/example/breeze0events/AdminEventDetail.java
- app/src/main/java/com/example/breeze0events/AdminFacilityActivity.java
- app/src/main/res/layout/remove_events_page.xml
Every time after clicking delete events button, it can't direct show the updated event list, you have to go back to main page and back. So adding a refresh button to solve this issue.
> Add refresh button

- app/src/androidTest/java/com/example/breeze0events/OrganizerEventActivityTest.java
have added the checkpoint to recognize whether we have successfully added the event into the database in the test method testGenerateQRFillFieldsSelectFacilityAndAddEvent
> add additional checkpoint to OrganizerEventActivityTest

- .idea/androidTestResultsUserPreferences.xml
- .idea/deploymentTargetSelector.xml
- app/src/androidTest/java/com/example/breeze0events/US020601.java
- app/src/androidTest/java/com/example/breeze0events/US030101.java
- app/src/androidTest/java/com/example/breeze0events/US030401.java
- app/src/main/java/com/example/breeze0events/OrganizerSamplingActivity.java
add test cases for US 02.06.01
> add test cases

- .idea/androidTestResultsUserPreferences.xml
- .idea/deploymentTargetSelector.xml
- app/src/androidTest/java/com/example/breeze0events/US020601.java
- app/src/androidTest/java/com/example/breeze0events/US030101.java
- app/src/androidTest/java/com/example/breeze0events/US030401.java
- app/src/main/java/com/example/breeze0events/OrganizerSamplingActivity.java
add test cases for US 02.06.01
> test cases

- app/src/main/java/com/example/breeze0events/Entrant.java
- app/src/main/java/com/example/breeze0events/EntrantLoginActivity.java
- app/src/main/java/com/example/breeze0events/OverallStorageController.java
add the attribute notifications to entrant class
> change the overallstoragecontroller

- app/build.gradle.kts
- app/src/main/java/com/example/breeze0events/OrganizerMapActivity.java
- app/src/main/res/layout/map_activity.xml
> Map function

- app/src/androidTest/java/com/example/breeze0events/OverallStorageControllerTest.java
- app/src/androidTest/java/com/example/breeze0events/US030201.java
- app/src/main/java/com/example/breeze0events/OrganizerMyListActivity.java
have successfully deleted the information of the event from each entrant which belongs to the event
> fixed bugs for deleting events

- .idea/deploymentTargetSelector.xml
- .idea/gradle.xml
- .idea/misc.xml
- app/src/main/java/com/example/breeze0events/Entrant.java
- app/src/main/java/com/example/breeze0events/OrganizerMapActivity.java
have updated the map view the location where entrants join the given event
> update the map

- app/src/main/java/com/example/breeze0events/AdminQRcode.java
- app/src/main/java/com/example/breeze0events/AdminSelectedEvents.java
after delete qr code, back to eventlist page, in case user click qr code right after deleting, but it is not updated yet.
> update delete qr code

- app/src/main/java/com/example/breeze0events/Entrant.java
- app/src/main/java/com/example/breeze0events/EntrantMyListAdapter.java
- app/src/main/java/com/example/breeze0events/EntrantMylistActivity.java
- app/src/main/java/com/example/breeze0events/EntrantNotificationActivity.java
- app/src/main/java/com/example/breeze0events/EntrantNotificationAdapter.java
- app/src/main/java/com/example/breeze0events/NewPair.java
- app/src/main/java/com/example/breeze0events/OrganizerNotificationActivity.java
- app/src/main/java/com/example/breeze0events/OrganizerSamplingActivity.java
- app/src/main/java/com/example/breeze0events/OverallStorageController.java
> change Pair into NewPair

- app/src/main/java/com/example/breeze0events/Event.java
- app/src/main/java/com/example/breeze0events/OrganizerEditEventActivity.java
- app/src/main/java/com/example/breeze0events/OrganizerEventActivity.java
- app/src/main/java/com/example/breeze0events/OrganizerMapActivity.java
- app/src/main/java/com/example/breeze0events/OrganizerMyListActivity.java
- app/src/main/java/com/example/breeze0events/OverallStorageController.java
- app/src/main/res/layout/organizer_edit_event_activity.xml
- app/src/main/res/layout/organizer_event_activity.xml
add the geolocation authorization button
> geolocation authorization

- .idea/misc.xml
- app/src/main/java/com/example/breeze0events/AdminEntrantProfileActivity.java
- app/src/main/java/com/example/breeze0events/AdminOperateActivity.java
- app/src/main/java/com/example/breeze0events/AdminentrantProfile.java
- app/src/main/res/layout/admin_main_activity.xml
- app/src/main/res/layout/entrant_profile_list.xml
- app/src/main/res/layout/organization_profile_recycle.xml
i adjust some button position and improve the back button's function
> admin change

- app/src/main/java/com/example/breeze0events/OrganizerEditEventActivity.java
- app/src/main/java/com/example/breeze0events/OrganizerEventActivity.java
start date cannot be after end date
> add the constarint

- app/src/androidTest/java/com/example/breeze0events/OverallStorageControllerTest.java
- app/src/androidTest/java/com/example/breeze0events/US010102.java
- app/src/androidTest/java/com/example/breeze0events/US020102.java
- app/src/androidTest/java/com/example/breeze0events/US030101.java
- app/src/androidTest/java/com/example/breeze0events/US030201.java
- app/src/androidTest/java/com/example/breeze0events/US030401.java
edit the test cases to match the new class
> edit the test cases

- app/src/main/java/com/example/breeze0events/AdminEventActivity.java
- app/src/main/java/com/example/breeze0events/AdminEventDetail.java
- app/src/main/java/com/example/breeze0events/AdminSelectedEvents.java
handle Poster "Transaction Too Large Exception" error that cannot pass data to event detail. Using a shared resource instead of passing large data
> Transaction Too Large Exception

- .idea/androidTestResultsUserPreferences.xml
- .idea/deploymentTargetSelector.xml
- app/src/androidTest/java/com/example/breeze0events/US020503.java
- app/src/main/java/com/example/breeze0events/OrganizerMyListActivity.java
have added test cases US020503
> have added test cases

- .idea/androidTestResultsUserPreferences.xml
- .idea/deploymentTargetSelector.xml
- app/src/androidTest/java/com/example/breeze0events/US020202.java
have added the test cases for the markers of the map view.
> have added the map view

- app/src/androidTest/java/com/example/breeze0events/US030302.java
- app/src/main/java/com/example/breeze0events/AdminQRcode.java
This test is to delete hashed QR code data from database and in app view
> Update UI testing named US030302

- app/src/androidTest/java/com/example/breeze0events/US030101.java
- app/src/androidTest/java/com/example/breeze0events/US030302.java
- app/src/androidTest/java/com/example/breeze0events/US030401.java
- app/src/main/java/com/example/breeze0events/AdminBrowseImage.java
- app/src/main/java/com/example/breeze0events/AdminEventDetail.java
- app/src/main/java/com/example/breeze0events/AdminQRcode.java
> Run all test case successfully
